# Generated by Django 4.0.3 on 2022-04-21 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='horoscope_on_30_days',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='horoscope',
            name='slug',
            field=models.SlugField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='horoscope',
            name='horoscope_description',
            field=models.TextField(null=True),
        ),
    ]
