# Generated by Django 4.0.3 on 2022-05-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_horoscope_horoscope_on_30_days_horoscope_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='horoscope',
            name='zodiac_mini_description',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
