# Generated by Django 4.0.3 on 2022-04-24 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=50)),
                ('translation', models.CharField(max_length=50, null=True)),
                ('transcription', models.CharField(max_length=50, null=True)),
                ('context', models.TextField(default='')),
            ],
        ),
    ]
