# Generated by Django 4.0.3 on 2022-05-01 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english_grammar_dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictionary',
            name='transcription',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dictionary',
            name='translation',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
